export interface AreaMarker {
  name: string;
  x: number;
  y: number;
}

const cityAreas: Record<string, AreaMarker[]> = {
  Delhi: [
    { name: "Connaught Place", x: 50, y: 40 },
    { name: "Dwarka", x: 15, y: 65 },
    { name: "Rohini", x: 35, y: 12 },
    { name: "Saket", x: 45, y: 72 },
    { name: "Lajpat Nagar", x: 58, y: 55 },
    { name: "Karol Bagh", x: 40, y: 32 },
    { name: "Chandni Chowk", x: 52, y: 35 },
    { name: "Nehru Place", x: 55, y: 65 },
    { name: "Janakpuri", x: 22, y: 55 },
    { name: "Pitampura", x: 32, y: 18 },
    { name: "Greater Kailash", x: 50, y: 68 },
    { name: "Vasant Kunj", x: 35, y: 78 },
    { name: "Mayur Vihar", x: 70, y: 48 },
    { name: "Preet Vihar", x: 68, y: 38 },
    { name: "Rajouri Garden", x: 28, y: 42 },
    { name: "Hauz Khas", x: 42, y: 62 },
    { name: "ITO", x: 55, y: 42 },
    { name: "Lodhi Colony", x: 48, y: 52 },
    { name: "Defence Colony", x: 52, y: 58 },
    { name: "Okhla", x: 60, y: 75 },
  ],
  Mumbai: [
    { name: "Bandra", x: 38, y: 42 },
    { name: "Andheri", x: 32, y: 30 },
    { name: "Colaba", x: 52, y: 88 },
    { name: "Powai", x: 62, y: 25 },
    { name: "Dadar", x: 45, y: 55 },
    { name: "Worli", x: 40, y: 60 },
    { name: "Juhu", x: 28, y: 38 },
    { name: "Goregaon", x: 25, y: 22 },
    { name: "Malad", x: 22, y: 18 },
    { name: "Borivali", x: 18, y: 12 },
    { name: "Kurla", x: 50, y: 40 },
    { name: "Chembur", x: 58, y: 48 },
    { name: "Mulund", x: 65, y: 18 },
    { name: "Thane", x: 70, y: 12 },
    { name: "Navi Mumbai", x: 75, y: 45 },
    { name: "Vashi", x: 72, y: 52 },
    { name: "Vikhroli", x: 60, y: 32 },
    { name: "Lower Parel", x: 42, y: 65 },
    { name: "Fort", x: 50, y: 82 },
    { name: "Marine Lines", x: 48, y: 75 },
  ],
  Jaipur: [
    { name: "Mansarovar", x: 22, y: 28 },
    { name: "Malviya Nagar", x: 55, y: 65 },
    { name: "Vaishali Nagar", x: 15, y: 55 },
    { name: "Jagatpura", x: 78, y: 72 },
    { name: "C-Scheme", x: 50, y: 35 },
    { name: "Bani Park", x: 42, y: 18 },
    { name: "Tonk Road", x: 55, y: 55 },
    { name: "Sodala", x: 35, y: 38 },
    { name: "Raja Park", x: 60, y: 38 },
    { name: "Sanganer", x: 50, y: 82 },
    { name: "Sitapura", x: 70, y: 85 },
    { name: "Jhotwara", x: 28, y: 22 },
    { name: "Ajmer Road", x: 18, y: 42 },
    { name: "Durgapura", x: 65, y: 58 },
    { name: "Pratap Nagar", x: 45, y: 48 },
    { name: "Adarsh Nagar", x: 48, y: 25 },
    { name: "Vidhyadhar Nagar", x: 38, y: 15 },
    { name: "Shyam Nagar", x: 30, y: 45 },
    { name: "Nirman Nagar", x: 38, y: 52 },
    { name: "Bapu Nagar", x: 58, y: 45 },
  ],
  Bangalore: [
    { name: "Koramangala", x: 55, y: 58 },
    { name: "Whitefield", x: 82, y: 38 },
    { name: "Indiranagar", x: 62, y: 42 },
    { name: "Jayanagar", x: 45, y: 65 },
    { name: "Electronic City", x: 50, y: 88 },
    { name: "Malleshwaram", x: 38, y: 28 },
    { name: "HSR Layout", x: 58, y: 68 },
    { name: "BTM Layout", x: 52, y: 65 },
    { name: "Marathahalli", x: 72, y: 42 },
    { name: "Hebbal", x: 48, y: 15 },
    { name: "Yelahanka", x: 42, y: 8 },
    { name: "Banashankari", x: 40, y: 72 },
    { name: "JP Nagar", x: 45, y: 75 },
    { name: "Rajajinagar", x: 35, y: 35 },
    { name: "Basavanagudi", x: 42, y: 55 },
    { name: "MG Road", x: 52, y: 42 },
    { name: "Domlur", x: 58, y: 48 },
    { name: "Sarjapur Road", x: 68, y: 65 },
    { name: "Bellandur", x: 65, y: 55 },
    { name: "Bannerghatta", x: 48, y: 82 },
  ],
  Chennai: [
    { name: "T. Nagar", x: 38, y: 48 },
    { name: "Adyar", x: 52, y: 62 },
    { name: "Anna Nagar", x: 32, y: 28 },
    { name: "Velachery", x: 48, y: 75 },
    { name: "Mylapore", x: 58, y: 52 },
    { name: "Guindy", x: 40, y: 58 },
    { name: "Tambaram", x: 42, y: 88 },
    { name: "Porur", x: 22, y: 52 },
    { name: "Sholinganallur", x: 62, y: 78 },
    { name: "Thoraipakkam", x: 60, y: 72 },
    { name: "Chromepet", x: 38, y: 82 },
    { name: "Perambur", x: 48, y: 25 },
    { name: "Egmore", x: 50, y: 38 },
    { name: "Nungambakkam", x: 45, y: 42 },
    { name: "Royapettah", x: 52, y: 45 },
    { name: "Kilpauk", x: 42, y: 32 },
    { name: "Ambattur", x: 28, y: 22 },
    { name: "Avadi", x: 20, y: 15 },
    { name: "Besant Nagar", x: 58, y: 58 },
    { name: "OMR", x: 65, y: 68 },
  ],
  Kolkata: [
    { name: "Salt Lake", x: 65, y: 32 },
    { name: "Park Street", x: 48, y: 48 },
    { name: "Howrah", x: 28, y: 45 },
    { name: "New Town", x: 78, y: 25 },
    { name: "Ballygunge", x: 55, y: 55 },
    { name: "Dum Dum", x: 48, y: 18 },
    { name: "Jadavpur", x: 52, y: 65 },
    { name: "Behala", x: 38, y: 75 },
    { name: "Tollygunge", x: 45, y: 68 },
    { name: "Alipore", x: 42, y: 58 },
    { name: "Baranagar", x: 42, y: 22 },
    { name: "Gariahat", x: 52, y: 58 },
    { name: "Esplanade", x: 45, y: 45 },
    { name: "Sealdah", x: 50, y: 40 },
    { name: "Rajarhat", x: 75, y: 22 },
    { name: "Lake Town", x: 58, y: 28 },
    { name: "Bhowanipore", x: 45, y: 55 },
    { name: "Beliaghata", x: 55, y: 38 },
    { name: "Kasba", x: 58, y: 62 },
    { name: "Barrackpore", x: 48, y: 8 },
  ],
  Hyderabad: [
    { name: "Banjara Hills", x: 38, y: 42 },
    { name: "HITEC City", x: 18, y: 48 },
    { name: "Secunderabad", x: 55, y: 22 },
    { name: "Gachibowli", x: 22, y: 62 },
    { name: "Jubilee Hills", x: 32, y: 38 },
    { name: "Charminar", x: 58, y: 68 },
    { name: "Madhapur", x: 25, y: 45 },
    { name: "Kukatpally", x: 28, y: 28 },
    { name: "Kondapur", x: 22, y: 38 },
    { name: "LB Nagar", x: 72, y: 72 },
    { name: "Dilsukhnagar", x: 65, y: 65 },
    { name: "Begumpet", x: 45, y: 28 },
    { name: "Ameerpet", x: 38, y: 32 },
    { name: "Nampally", x: 48, y: 52 },
    { name: "Mehdipatnam", x: 38, y: 55 },
    { name: "Uppal", x: 72, y: 42 },
    { name: "Miyapur", x: 15, y: 28 },
    { name: "Shamshabad", x: 42, y: 85 },
    { name: "Tarnaka", x: 60, y: 32 },
    { name: "Kompally", x: 48, y: 12 },
  ],
  Pune: [
    { name: "Koregaon Park", x: 62, y: 38 },
    { name: "Hinjewadi", x: 15, y: 32 },
    { name: "Kothrud", x: 32, y: 48 },
    { name: "Viman Nagar", x: 72, y: 28 },
    { name: "Shivajinagar", x: 48, y: 42 },
    { name: "Hadapsar", x: 75, y: 62 },
    { name: "Baner", x: 25, y: 35 },
    { name: "Aundh", x: 30, y: 28 },
    { name: "Wakad", x: 18, y: 28 },
    { name: "Kharadi", x: 78, y: 38 },
    { name: "Magarpatta", x: 72, y: 55 },
    { name: "Deccan", x: 42, y: 45 },
    { name: "Swargate", x: 48, y: 55 },
    { name: "Katraj", x: 45, y: 72 },
    { name: "Kondhwa", x: 58, y: 68 },
    { name: "Pimpri", x: 32, y: 15 },
    { name: "Chinchwad", x: 25, y: 12 },
    { name: "Camp", x: 55, y: 48 },
    { name: "Yerwada", x: 62, y: 32 },
    { name: "Bibwewadi", x: 48, y: 62 },
  ],
  Ahmedabad: [
    { name: "Navrangpura", x: 42, y: 38 },
    { name: "SG Highway", x: 22, y: 52 },
    { name: "Maninagar", x: 62, y: 65 },
    { name: "Satellite", x: 28, y: 48 },
    { name: "Bopal", x: 25, y: 72 },
    { name: "Vastrapur", x: 32, y: 42 },
    { name: "Paldi", x: 42, y: 55 },
    { name: "Prahlad Nagar", x: 30, y: 58 },
    { name: "Thaltej", x: 25, y: 42 },
    { name: "Bodakdev", x: 28, y: 45 },
    { name: "Chandkheda", x: 45, y: 12 },
    { name: "Gota", x: 38, y: 15 },
    { name: "Memnagar", x: 38, y: 35 },
    { name: "Ashram Road", x: 48, y: 45 },
    { name: "Ellis Bridge", x: 45, y: 42 },
    { name: "Shahibag", x: 52, y: 28 },
    { name: "Naroda", x: 68, y: 22 },
    { name: "Vastral", x: 72, y: 55 },
    { name: "Isanpur", x: 65, y: 62 },
    { name: "Nikol", x: 70, y: 35 },
  ],
  Lucknow: [
    { name: "Hazratganj", x: 48, y: 42 },
    { name: "Gomti Nagar", x: 65, y: 48 },
    { name: "Aliganj", x: 38, y: 28 },
    { name: "Indira Nagar", x: 62, y: 35 },
    { name: "Aminabad", x: 42, y: 52 },
    { name: "Alambagh", x: 32, y: 68 },
    { name: "Charbagh", x: 38, y: 55 },
    { name: "Mahanagar", x: 42, y: 32 },
    { name: "Rajajipuram", x: 28, y: 42 },
    { name: "Vikas Nagar", x: 55, y: 28 },
    { name: "Chinhat", x: 75, y: 38 },
    { name: "Jankipuram", x: 45, y: 15 },
    { name: "Ashiyana", x: 52, y: 72 },
    { name: "Telibagh", x: 48, y: 78 },
    { name: "Faizabad Road", x: 58, y: 22 },
    { name: "Kanpur Road", x: 25, y: 62 },
    { name: "Aashiana", x: 50, y: 68 },
    { name: "Eldeco", x: 70, y: 55 },
    { name: "Sushant Golf City", x: 68, y: 65 },
    { name: "Gomti Nagar Ext", x: 75, y: 52 },
  ],
  Chandigarh: [
    { name: "Sector 17", x: 48, y: 38 },
    { name: "Sector 22", x: 42, y: 52 },
    { name: "Sector 35", x: 52, y: 62 },
    { name: "Sector 43", x: 38, y: 68 },
    { name: "Manimajra", x: 72, y: 28 },
    { name: "Panchkula", x: 82, y: 32 },
    { name: "Sector 7", x: 42, y: 22 },
    { name: "Sector 8", x: 45, y: 25 },
    { name: "Sector 9", x: 48, y: 28 },
    { name: "Sector 15", x: 50, y: 32 },
    { name: "Sector 26", x: 55, y: 48 },
    { name: "Sector 34", x: 48, y: 58 },
    { name: "Sector 44", x: 40, y: 72 },
    { name: "Sector 47", x: 35, y: 78 },
    { name: "Industrial Area", x: 65, y: 42 },
    { name: "IT Park", x: 68, y: 48 },
    { name: "Mohali", x: 55, y: 82 },
    { name: "Zirakpur", x: 78, y: 18 },
    { name: "Sector 20", x: 45, y: 42 },
    { name: "Sector 32", x: 50, y: 55 },
  ],
  Bhopal: [
    { name: "MP Nagar", x: 48, y: 42 },
    { name: "Arera Colony", x: 52, y: 52 },
    { name: "Kolar Road", x: 65, y: 68 },
    { name: "Habibganj", x: 42, y: 48 },
    { name: "New Market", x: 38, y: 35 },
    { name: "Misrod", x: 58, y: 75 },
    { name: "Hoshangabad Road", x: 55, y: 62 },
    { name: "Bairagarh", x: 22, y: 28 },
    { name: "Govindpura", x: 62, y: 35 },
    { name: "Shahpura", x: 48, y: 58 },
    { name: "BHEL", x: 70, y: 55 },
    { name: "Ayodhya Nagar", x: 55, y: 48 },
    { name: "Ashoka Garden", x: 52, y: 38 },
    { name: "TT Nagar", x: 42, y: 38 },
    { name: "Piplani", x: 68, y: 42 },
    { name: "Chuna Bhatti", x: 45, y: 52 },
    { name: "Shivaji Nagar", x: 38, y: 42 },
    { name: "Raisen Road", x: 72, y: 32 },
    { name: "Mandideep", x: 75, y: 78 },
    { name: "Trilanga", x: 58, y: 42 },
  ],
  Indore: [
    { name: "Vijay Nagar", x: 42, y: 32 },
    { name: "Palasia", x: 48, y: 48 },
    { name: "Sapna Sangeeta", x: 45, y: 42 },
    { name: "AB Road", x: 52, y: 58 },
    { name: "Bhawarkua", x: 40, y: 40 },
    { name: "Rajwada", x: 50, y: 52 },
    { name: "MG Road", x: 48, y: 45 },
    { name: "Scheme 78", x: 35, y: 28 },
    { name: "Scheme 54", x: 38, y: 35 },
    { name: "Rau", x: 28, y: 72 },
    { name: "Nipania", x: 30, y: 25 },
    { name: "Sudama Nagar", x: 55, y: 55 },
    { name: "Annapurna", x: 45, y: 55 },
    { name: "Bhanwarkuan", x: 42, y: 42 },
    { name: "LIG Colony", x: 52, y: 38 },
    { name: "Tilak Nagar", x: 48, y: 62 },
    { name: "Geeta Bhawan", x: 50, y: 48 },
    { name: "Khajrana", x: 62, y: 45 },
    { name: "Banganga", x: 55, y: 65 },
    { name: "Super Corridor", x: 25, y: 32 },
  ],
  Surat: [
    { name: "Adajan", x: 32, y: 42 },
    { name: "Vesu", x: 38, y: 62 },
    { name: "Athwa", x: 48, y: 48 },
    { name: "Katargam", x: 52, y: 28 },
    { name: "Varachha", x: 58, y: 32 },
    { name: "Piplod", x: 40, y: 55 },
    { name: "City Light", x: 35, y: 52 },
    { name: "Ring Road", x: 55, y: 42 },
    { name: "Udhna", x: 62, y: 55 },
    { name: "Pandesara", x: 65, y: 62 },
    { name: "Dumas", x: 25, y: 72 },
    { name: "Pal", x: 28, y: 48 },
    { name: "Althan", x: 42, y: 45 },
    { name: "Ghodod Road", x: 50, y: 38 },
    { name: "Parle Point", x: 38, y: 48 },
    { name: "Magob", x: 55, y: 22 },
    { name: "Majura Gate", x: 52, y: 45 },
    { name: "Dindoli", x: 60, y: 68 },
    { name: "Olpad", x: 22, y: 35 },
    { name: "Kim", x: 18, y: 28 },
  ],
  Patna: [
    { name: "Boring Road", x: 42, y: 42 },
    { name: "Kankarbagh", x: 38, y: 52 },
    { name: "Patliputra", x: 55, y: 32 },
    { name: "Rajendra Nagar", x: 48, y: 58 },
    { name: "Danapur", x: 22, y: 48 },
    { name: "Bailey Road", x: 50, y: 40 },
    { name: "Ashok Rajpath", x: 58, y: 35 },
    { name: "Exhibition Road", x: 48, y: 45 },
    { name: "Fraser Road", x: 52, y: 42 },
    { name: "Gandhi Maidan", x: 50, y: 38 },
    { name: "Anisabad", x: 55, y: 48 },
    { name: "Saguna More", x: 25, y: 55 },
    { name: "Phulwari Sharif", x: 32, y: 62 },
    { name: "Naubatpur", x: 28, y: 72 },
    { name: "Digha", x: 68, y: 28 },
    { name: "Khagaul", x: 18, y: 42 },
    { name: "Jakkanpur", x: 62, y: 52 },
    { name: "Rukanpura", x: 45, y: 35 },
    { name: "Mahendru", x: 62, y: 38 },
    { name: "Shastri Nagar", x: 45, y: 48 },
  ],
};

const stateNames: Record<string, string> = {
  Delhi: "Delhi NCR",
  Mumbai: "Maharashtra",
  Jaipur: "Rajasthan",
  Bangalore: "Karnataka",
  Chennai: "Tamil Nadu",
  Kolkata: "West Bengal",
  Hyderabad: "Telangana",
  Pune: "Maharashtra",
  Ahmedabad: "Gujarat",
  Lucknow: "Uttar Pradesh",
  Chandigarh: "Chandigarh UT",
  Bhopal: "Madhya Pradesh",
  Indore: "Madhya Pradesh",
  Surat: "Gujarat",
  Patna: "Bihar",
};

export const getCityAreas = (city: string): AreaMarker[] => {
  return cityAreas[city] || cityAreas.Delhi;
};

export const getCityState = (city: string): string => {
  return stateNames[city] || "India";
};

export const allCityNames = Object.keys(cityAreas);
