import { Download } from "lucide-react";
import { toast } from "sonner";
import { getAqiCategory } from "@/lib/cityData";

interface DownloadReportProps {
  city: string;
  aqi: number;
  pm25: number;
  co2: number;
  humidity: number;
  history7: number[];
}

const DownloadReport = ({ city, aqi, pm25, co2, humidity, history7 }: DownloadReportProps) => {
  const handleDownload = () => {
    const cat = getAqiCategory(aqi);
    const avg7 = Math.round(history7.reduce((a, b) => a + b, 0) / history7.length);
    const max7 = Math.max(...history7);
    const min7 = Math.min(...history7);
    const date = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });

    const report = `
=============================================
       WEEKLY AQI REPORT — ${city.toUpperCase()}
=============================================
Date: ${date}

CURRENT STATUS
  AQI:        ${aqi} (${cat.label})
  PM2.5:      ${pm25} µg/m³
  CO₂:        ${co2} ppm
  Humidity:   ${humidity}%

WEEKLY SUMMARY (Last 7 Days)
  Average AQI: ${avg7}
  Highest AQI: ${max7}
  Lowest AQI:  ${min7}
  Daily:       ${history7.join(", ")}

RECOMMENDATION
  ${aqi <= 50 ? "Air quality is good. All outdoor activities safe." :
    aqi <= 100 ? "Acceptable air quality. Sensitive groups should be cautious." :
    aqi <= 200 ? "Unhealthy for sensitive groups. Limit outdoor exertion." :
    "Hazardous conditions. Stay indoors and use air purifiers."}

=============================================
Generated by PM2.5 Dashboard
    `.trim();

    const blob = new Blob([report], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `AQI_Report_${city}_${new Date().toISOString().slice(0, 10)}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    toast.success("AQI Weekly Report downloaded!", { description: a.download });
  };

  return (
    <button onClick={handleDownload}
      className="flex items-center gap-2 px-5 py-2.5 rounded-xl bg-primary text-primary-foreground text-sm font-semibold hover:bg-primary/90 transition-all duration-300 glow-primary hover:shadow-lg hover:scale-105">
      <Download className="w-4 h-4" />
      Download Weekly Report
    </button>
  );
};

export default DownloadReport;
